#!/usr/bin/env bash
set -euo pipefail

#
# Commands
#

PYTHON="${PYTHON:-python}"

#
# Variables
#

ARTIFACTS_DIR="${ARTIFACTS_DIR:-dist}"

#
#
#

. scripts/library.sh

relay::sdk::python::release_check
$PYTHON -m twine upload $( relay::sdk::python::package_artifacts "${ARTIFACTS_DIR}" )
